CREATE TABLE banco (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(3) NOT NULL,
    nome VARCHAR(50) NOT NULL
);

INSERT INTO banco (codigo, nome) VALUES ('001', 'Banco do Brasil');
INSERT INTO banco (codigo, nome) VALUES ('237', 'Banco Bradesco');
INSERT INTO banco (codigo, nome) VALUES ('341', 'Banco Itaú');